using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace WebApplication1
{
    public partial class WebForm1 : System.Web.UI.Page
    {
        protected void Page_Load(object sender, EventArgs e)
        {

        }

        protected void CheckBox1_CheckedChanged(object sender, EventArgs e)
        {
            Panel1.Visible = CheckBox1.Checked;
        }

        protected void CheckBox2_CheckedChanged(object sender, EventArgs e)
        {
            GridView1.AutoGenerateEditButton = CheckBox2.Checked;
        }

        protected void CheckBox3_CheckedChanged(object sender, EventArgs e)
        {
            GridView1.AutoGenerateDeleteButton = CheckBox3.Checked;
        }

        protected void Button1_Click(object sender, EventArgs e)
        {
            SqlDataSource1.Insert();
        }

        protected void CheckBox4_CheckedChanged(object sender, EventArgs e)
        {
            Panel2.Visible = CheckBox4.Checked;
        }

        protected void CheckBox5_CheckedChanged(object sender, EventArgs e)
        {
            GridView2.AutoGenerateEditButton = CheckBox5.Checked;
        }

        protected void Button2_Click(object sender, EventArgs e)
        {
            SqlDataSource2.Insert();
        }

        protected void GridView1_SelectedIndexChanged(object sender, EventArgs e)
        {
            CheckBox4.Visible = true;
            CheckBox5.Visible = true;
        }
    }
}